id: P005369
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 11:46:41.416657
source_metadata:
  id: bdr:W1KG14132
  title: བཀའ་བབས་བདུན་ལྡན་གྱི་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    d0903c22a84c4b05b56aced1c596fb59:
      image_group_id: I1KG14321
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
